api_platform:
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    multipart: ["multipart/form-data"]
  swagger:
    versions: [3]
  title: "ACOO API"
  description: "API for ACOO project"
  version: "1.0.0"
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
