networks:
  apiacoo:
    external: true

services:
  app:
    image: bitnami/symfony
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
      - SYMFONY_DATABASE_HOST=database
      - DATABASE_URL=mysql://root:@database:3306/ACOO?serverVersion=8.0.32&charset=utf8mb4
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=root
      - SYMFONY_DATABASE_NAME=ACOO
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - "8080:8000"

  # web:
  #   image: nginx
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./templates:/etc/nginx/templates
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ACOO}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-root}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
    ports:
      - '3307:3306'

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '8025:8025'
      - '1025:1025'

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: http://database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  # Ajout du service API Platform
  api:
    image: api-platform/api-platform
    ports:
      - "80:80"
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data: {}
  ###< doctrine/doctrine-bundle ###
